### ISSUE TITLE
IndexError: list index out of range while scraping

### ISSUE THREAD

**Issue by satvikmaker** [harryandriyan/warta-scrap#20]
Hi,

I tried to run the project. It fails with IndexError: list index out of range.

```
2017-09-16 22:04:44 [scrapy.core.scraper] DEBUG: Scraped from <200 http://www.antaranews.com/terkini>
{'category': '',
 'date': '16/09/2017',
 'desc': '',
 'images': 'http://img.antaranews.com/new/2016/08/small/20160831Sergio-Aguero.jpg',
 'link': 'http://www.antaranews.com/berita/653083/manchester-city-gulung-watford-6-0-aguero-hattrick',
 'title': 'Manchester City gulung Watford 6-0, Aguero hattrick'}
2017-09-16 22:04:44 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.antaranews.com/terkini> (referer: None)
Traceback (most recent call last):
  File "/home/bozzmob/.virtualenvs/chidori/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/home/bozzmob/.virtualenvs/chidori/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/home/bozzmob/.virtualenvs/chidori/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/home/bozzmob/.virtualenvs/chidori/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/bozzmob/.virtualenvs/chidori/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/bozzmob/work/code/fxpi/chidori/rough/warta-scrap/antara/antara/spiders/antara_spider.py", line 25, in parse
    item['title'] = indek.xpath('div/div[@class="bxpd"]/h3/a/text()').extract()[0]
IndexError: list index out of range
```

**Comment by harryandriyan** [comment]
noted.
it's because there is an inappropriate xpath selector, will be fixed soon

**Comment by brandonmburroughs** [comment]
Hey.  I've fixed this now in [this commit](https://github.com/brandonmburroughs/warta-scrap/commit/e52b39824624ea90966a96748919f6dcfa41f599).  You were using `.extract()[0]` in some of your spiders instead of `.extract_first()`.  `extract_first()` does the same thing, but will appropriately return `None` if nothing is extracted.  I no longer get the `IndexError`.  I'll submit the PR tomorrow (for Hacktoberfest).  I also changed a few other small things.

1. You should use `reposnse.urljoin(<path>)` instead of string concatenation.  This will fail more gracefully and works better overall.
2. I used the more general print function (`from __future__ import print_function`) so that this works for Python 2 and 3.  This was the only thing preventing it being 2 and 3 compatible and it's an easy fix.
